### ISSUE TITLE
what is the version of Torch-Struct?

### ISSUE THREAD

**Issue by rujiewu** [Sy-Zhang/MMC-PCFG#1]
I installed the latest version of it with this command ‘pip install torch-struct’ ，and I got this error :

File "/data/code/mmc_pcfg/parsing/../lib/model/vpcfg/model.py", line 90, in forward_parser
    ll, span_margs = dist.inside_im
AttributeError: 'SentCFG' object has no attribute 'inside_im'

the source code of class 'SentCFG' is :
![1629287328](https://user-images.githubusercontent.com/43574852/129893036-b14c792a-6ba2-4893-87bd-44ef76993a8a.jpg)

**Comment by rujiewu** [comment]
Thanks for your work and code for enlightening me, and look forward to your answers

**Comment by Sy-Zhang** [comment]
> I installed the latest version of it with this command ‘pip install torch-struct’ ，and I got this error :
> 
> File "/data/code/mmc_pcfg/parsing/../lib/model/vpcfg/model.py", line 90, in forward_parser
> ll, span_margs = dist.inside_im
> AttributeError: 'SentCFG' object has no attribute 'inside_im'
> 
> the source code of class 'SentCFG' is :
> ![1629287328](https://user-images.githubusercontent.com/43574852/129893036-b14c792a-6ba2-4893-87bd-44ef76993a8a.jpg)

Thanks for your interest. Please check this version https://github.com/zhaoyanpeng/pytorch-struct
